### ISSUE TITLE
Put the updates in the Caches folder

### ISSUE THREAD

**Issue by robrix** [Squirrel/Squirrel.Mac#108]
Updates presumably don’t need to be backed up, and the semantics of the Caches folder as interpreted by e.g. Spotlight, Time Machine, etc., would seem to be a good fit for our updates.

https://halp.githubapp.com/inboxes/github-for-mac/discussions/a810dc6c85bb11e39b4018677bfa2224

**Comment by robrix** [comment]
Apparently [1Password has been seeing update failures](http://rickfillion.tumblr.com/post/110370590958/1password-update-failures) similar to some we’ve seen with Squirrel.

Michael Jurewitz comments that [it’s inappropriate for either `NSTemporaryDirectory()` or `Caches`](https://twitter.com/Jury/status/564166559468224513), so one ought to use `~/Library/Application Support/` and [be good about tidying](https://twitter.com/Jury/status/564166646269345793).

**Comment by jspahrsummers** [comment]
@robrix We currently use Application Support already—but it's untenable, because its contents are added to the LaunchServices database.

All of the temporary directory stuff is while _actually installing_ the update, not just when it's been downloaded.

**Comment by robrix** [comment]
Thanks for the context :bow:

**Comment by caesar** [comment]
Is there any progress with this? I see the ticket has been open for over two years...

I've just been facing this issue in Atom, which uses Squirrel to update.

Because it temporarily stores downloaded updates at `~/Library/Application Support/com.github.atom.ShipIt/`, these updates get included in Time Machine backups.
This causes a huge amount of backup churn - often several hundreds of megabytes on every hourly backup for an extended period.

Ideally updates in the process of being downloaded should be cached within `~/Library/Caches/`, which is excluded from Time Machine.
But failing that, at the very least the download path should be set to be excluded from Time Machine. (This can be done from the command line with `tmutil addexclusion <path>`.)

I reported this at atom/atom#11867, but it seems like it's actually a Squirrel issue.

**Comment by joshaber** [comment]
@caesar Nope, this is still an issue.

I agree we should store them in `~/Library/Caches/`.

**Comment by caesar** [comment]
Good work @joshaber, thanks!  🎉
