### ISSUE TITLE
Add CocoaPods as Supported Install method

### ISSUE THREAD

**Issue by abillingsley** [Squirrel/Squirrel.Mac#125]
### Description

[CocoaPods](http://cocoapods.org/) is a popular dependency manager for Objective-C projects.  It would be nice to be able to include Squirrel in applications via CocoaPods.
### CocoaPods Requirements
- [ ] Start using Tags for versioning
- [ ] Create [Podspec](http://guides.cocoapods.org/syntax/podspec.html)
- [ ] Publish the Podspec to [CocoaPod's Specs Repo](https://github.com/CocoaPods/Specs)

**Comment by cbenhagen** [comment]
@MarshallOfSound years have passed since this was filed and now Mantle and ReactiveCocoa both have CocoaPods  support. I am planning to build a Squirrel plugin for the Flutter framework and CocoaPods would make building that plugin a lot easier. Do you mind to reopen this issue? Or should I file a new one?

**Comment by MarshallOfSound** [comment]
@cbenhagen The same statement still kind of stands, as the only real "maintainer" of this repo we don't actually build Squirrel.Mac using xCode, we (Electron) build Squirrel.Mac from source using Chromiums build system and therefore use `gclient` to manage the dependencies on `Mantle` and `ReactiveObjC`.  Any PR you land here to that effect (using CocoaPods) would not really be utilized by anyone and I fear would become a maintenance burden 🤷
