### ISSUE TITLE
Installing updates without using squirrel.mac download updates code

### ISSUE THREAD

**Issue by juturu** [Squirrel/Squirrel.Mac#166]
Hi,

I'm building an app for Windows and MAC using Electron. I have an authenticated site hosting app updates. In my app side, i'm checking for updates and downloading updates (as a common modules for Windows and MAC). 

Is it possible to use just the quit and install from squirrel.mac module given the updates are downloaded in the same place as squirrel.mac? Or Is there any way to quit and install downloaded updates for MAC alone? For windows, i have this figured out.

Thanks!

**Comment by keithduncan** [comment]
@juturu I think you could achieve what you’re looking for with an `SQRLUpdater` subclass that overrides `checkForUpdatesCommand` to perform the update checking, download and preparation in your own manner. That command’s execution signal is expected to return an `SQRLDownloadedUpdate` instance which will then be provided to the rest of the installation machinery.

**Comment by juturu** [comment]
Thanks @keithduncan Can we add Authorization header to the check for updates GET call to enable using with secured end-points to this module? Users of the module could pass in the header contents to squirrel for making sure check for updates will succeed.

**Comment by keithduncan** [comment]
> Can we add Authorization header to the check for updates GET call to enable using with secured end-points

Yep, if you’re performing the HTTP request yourself your code will be responsible for that, if you’re using the built-in network request you can set headers on the `NSURLRequest` you provide to (`-[SQRLUpdater initWithUpdateRequest:]`)[https://github.com/Squirrel/Squirrel.Mac/blob/4a5041124602b061155e994429ed7958cae2411d/Squirrel/SQRLUpdater.h#L102-L112].

I’m not familiar with how the Squirrel.Mac API is exposed in the Electron bindings though, so that might be a question for the team responsible for them.

**Comment by juturu** [comment]
Thanks @keithduncan
